"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib
import json
import os
from pathlib import Path

import dj_database_url

from core_api.email_url import email_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-dev-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

# Comma-separated; docker-compose.yml sets it. Empty = Django's DEBUG
# default (localhost only), which rejects e.g. a Tailscale hostname.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

# nginx passes on X-Forwarded-Proto from the HTTPS front (Tailscale
# serve/Funnel), so absolute URLs Django builds (e.g. the MCP skills
# index) say https:// and CSRF origin checks match.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Full origins (scheme + host), comma-separated - needed for Django's
# own CSRF-protected forms (e.g. /admin/ login) behind HTTPS on a
# domain other than localhost. The API itself uses bearer tokens.
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Strict-Transport-Security max-age. 0 (default) sends no header; set it
# only once the app is served over HTTPS for good - browsers remember it.
SECURE_HSTS_SECONDS = int((os.environ.get("DJANGO_HSTS_SECONDS") or "0"))

# "self_hosted" (default) or "saas". A hosted install lets strangers sign
# up, so it turns off first-run setup (the first account would otherwise
# become app-wide Admin) - see AUTH_FIRST_RUN_SETUP below.
DEPLOYMENT_MODE = os.environ.get("DEPLOYMENT_MODE", "self_hosted")
if DEPLOYMENT_MODE not in ("self_hosted", "saas"):
    raise ValueError(f"DEPLOYMENT_MODE must be 'self_hosted' or 'saas', not {DEPLOYMENT_MODE!r}")

# Extra Django apps a downstream build adds (e.g. hosted billing) -
# comma-separated importable module names, pip-installed into this venv
# (docker-compose.yml's BACKEND_EXTRA_PIP). Each one is added to
# INSTALLED_APPS, its `urls` (if any) is mounted at api/v1/
# (config/urls.py), and its `host_settings.configure(settings)` (if any)
# runs at the end of this file to add/override settings. Empty here.
GOALNEXA_EXTENSIONS = [m.strip() for m in os.environ.get("GOALNEXA_EXTENSIONS", "").split(",") if m.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    # Backend rule mirrors the frontend one: a module's backend is an
    # importable Django app (packaged via that module's own
    # pyproject.toml, editable-installed here) rather than a copy - see
    # root AGENTS.md. Login/User/RefreshToken all come from this app.
    # System settings, audit log, email outbox (platform-core's) - see
    # core_api.system. Before the modules that register settings with it.
    'platform_system',
    'platform_auth',
    # Organization/OrgMembership. Its own JWTBearerAuthentication is
    # unused here - main's own DEFAULT_AUTHENTICATION_CLASSES
    # (platform_auth's ActorAuthentication, above) resolves request.user
    # to a real platform_auth.User already, and platform_org's views only
    # ever read request.user.id, so which one resolved it is invisible
    # to them.
    'platform_org',
    # Goal/Metric/CheckIn - the product's own core domain. No User/Org
    # table of its own either, same "module with no User table" pattern
    # as platform_org above.
    'goalnexa',
    # MCP server over every BaseViewSet above + personal access tokens
    # for MCP clients. Mounted at api/v1/mcp (config/urls.py).
    'platform_mcp',
    *GOALNEXA_EXTENSIONS,
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files (the admin's) from gunicorn - no
    # separate file server in front of the backend.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL (e.g. postgres://user:pass@host:5432/goalnexa) - unset =
# the local SQLite file, fine for a single-user self-host. Postgres for
# anything with real traffic or more than one backend process.
DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get("DATABASE_URL") or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=int((os.environ.get("DATABASE_CONN_MAX_AGE") or "60")),
        conn_health_checks=True,
    )
}


# Shared by every gunicorn worker (and replica) - the auth rate limits
# count here, and a per-process cache would give each worker its own
# count. The table comes from `manage.py createcachetable`, which the
# compose files run with migrate.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# `manage.py collectstatic` target (the backend image runs it at build).
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Compressed, not Manifest: a manifest storage raises on any file
    # missing from the manifest, which breaks tests/dev that never ran
    # collectstatic.
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# --- platform_auth app config (same settings it reads via django.conf.settings
# in its own security.py/views - see apps/platform-auth/backend/config/settings.py
# for the reference values) ---
JWT_SECRET = os.environ.get("JWT_SECRET", "dev-only-insecure-jwt-secret")
JWT_ACCESS_TTL_MINUTES = float(os.environ.get("JWT_ACCESS_TTL_MINUTES", "15"))
JWT_REFRESH_TTL_DAYS = int(os.environ.get("JWT_REFRESH_TTL_DAYS", "30"))
REFRESH_COOKIE_NAME = "refresh_token"
REFRESH_COOKIE_SECURE = os.environ.get("DJANGO_DEBUG", "true").lower() != "true"
# main is the top-level app, not mounted under a gateway path prefix
# itself - unlike platform-auth's own standalone deployment (which sets
# this to e.g. "/platform-auth"), this stays empty.
URL_PREFIX = ""
# First-run setup (the first account becomes app-wide Admin). Off when
# hosted: signup works from the first account on, and the operator's
# own admin comes from `manage.py grant_role <email> Admin`.
AUTH_FIRST_RUN_SETUP = DEPLOYMENT_MODE != "saas"

# --- Single sign-on (platform_auth/sso.py): OpenID Connect providers.
# All three set = "Sign in with ..." on the login page. The redirect URI
# to register at the provider: <this app's address>/api/v1/auth/sso/callback.
OIDC_ISSUER = os.environ.get("OIDC_ISSUER", "")
OIDC_CLIENT_ID = os.environ.get("OIDC_CLIENT_ID", "")
OIDC_CLIENT_SECRET = os.environ.get("OIDC_CLIENT_SECRET", "")
OIDC_SCOPES = os.environ.get("OIDC_SCOPES") or "openid email profile"
# Treat the provider's email as verified when it sends no `email_verified`
# claim (Microsoft Entra ID). Only for a provider you run or trust.
OIDC_TRUST_EMAIL = (os.environ.get("OIDC_TRUST_EMAIL") or "").lower() in ("1", "true", "yes")
# Only when the address Django sees isn't the public one.
OIDC_REDIRECT_URI = os.environ.get("OIDC_REDIRECT_URI", "")
# More providers, each with its own button: a JSON list of {"id", "label",
# "issuer", "client_id", "client_secret"} (optional "scopes",
# "trust_email"). Same redirect URI as above.
OIDC_PROVIDERS = json.loads(os.environ.get("OIDC_PROVIDERS") or "[]")

# --- platform_mcp app config (all optional) ---
# The MCP server's serverInfo name.
MCP_SERVER_NAME = "goalnexa"
# What every personal access token starts with - makes a leaked one
# recognizable (e.g. to secret scanners) and tells it apart from a JWT.
MCP_TOKEN_PREFIX = "gnx_"
# The resources an AI client gets tools for: what tracking goals takes,
# not the administration (users, roles, system settings - those stay in
# the web app). `MCP_RESOURCES=*` in the environment exposes every
# resource; a comma-separated list replaces this one.
MCP_RESOURCES = [
    "orgs", "org-members", "org-invitations",
    "goals", "goal-members", "metrics", "check-ins",
    "cycles", "goal-scores", "activities", "goal-comments",
]
if os.environ.get("MCP_RESOURCES", "").strip() == "*":
    MCP_RESOURCES = None
elif os.environ.get("MCP_RESOURCES"):
    MCP_RESOURCES = [name.strip() for name in os.environ["MCP_RESOURCES"].split(",") if name.strip()]
# ChatGPT's domain verification token (platform_mcp.wellknown_urls).
MCP_OPENAI_APPS_CHALLENGE = os.environ.get("MCP_OPENAI_APPS_CHALLENGE", "")

# RBAC (platform_auth.rbac) on every BaseViewSet resource, via
# platform-core's access-policy hook - see platform-auth's AGENTS.md.
CORE_API_ACCESS_POLICY = "platform_auth.rbac.policy.RBACPolicy"
# A role can be held app-wide or within one organization.
RBAC_SCOPE_ENDPOINT = "/api/v1/orgs"
RBAC_SCOPE_LABEL = "Organization"
# Created on migrate when missing. Member (every new user, app-wide) gets
# the everyday resources; managing users/roles is Admin's. A resource
# added later: list it here in the same release - its new permissions
# are added to the EXISTING roles whose patterns match (platform-auth's
# sync_catalog), so installs that already have these roles get it too.
RBAC_DEFAULT_ROLES = [
    {"name": "Admin", "description": "Full access, including users and roles.", "grants_all": True},
    {
        "name": "Member",
        "description": "Everyday use: goals, metrics, check-ins, organizations.",
        "is_default": True,
        # Within an org, who may manage its members and invitations is the
        # org's own owner/admin role (platform-org's OrgRole), on top of this.
        "permissions": [
            "goals.*", "goal-members.*", "metrics.*", "check-ins.*", "cycles.*", "goal-scores.*",
            "activities.*", "goal-comments.*", "orgs.*", "org-members.*", "org-invitations.*",
        ],
    },
    {
        "name": "Viewer",
        "description": "Read-only - e.g. held within one organization.",
        "permissions": [
            "goals.view", "goal-members.view", "metrics.view", "check-ins.view", "cycles.view", "goal-scores.view",
            "activities.view", "goal-comments.view", "orgs.view", "org-members.view",
        ],
    },
]

# --- Outgoing email (platform_system's outbox) ---
# EMAIL_URL: smtp://user:pass@host:587, smtps://...:465, or console://
# (development). Unset: nothing is sent - password reset and email
# verification can't work. EMAIL_FROM: the sender address; its display
# name is a system setting ("Sender name").
globals().update(email_settings(os.environ.get("EMAIL_URL"), os.environ.get("EMAIL_FROM")))

# Defaults for system settings (core_api.system) - what a setting reads
# until an admin saves one, or its env variable locks it. Hosted, new
# accounts must verify their email.
SYSTEM_SETTING_DEFAULTS = {
    "auth.require_email_verification": DEPLOYMENT_MODE == "saas",
}

# --- goalnexa app config (all optional) ---
# Check-ins posted by scripts/webhooks with a metric's ingest token
# (goalnexa/views/ingest.py), per metric.
GOALNEXA_INGEST_RATE = os.environ.get("GOALNEXA_INGEST_RATE") or "60/min"
# Where reminders link back to; unset = the host each user saved their
# reminder settings from.
GOALNEXA_PUBLIC_URL = os.environ.get("GOALNEXA_PUBLIC_URL", "")
# Which Apprise URL schemes a user may send reminders to (None = any).
# Hosted, only services with a fixed host: a webhook (json://, form://),
# a self-hosted ntfy/gotify or an SMTP server would let a stranger make
# the server call its own network.
GOALNEXA_REMINDER_SCHEMES = (
    None
    if DEPLOYMENT_MODE != "saas"
    else ["tgram", "discord", "slack", "msteams", "pover", "pbul", "pushed", "join", "line"]
)

# platform-org has no User table: members' names/emails, and the email an
# invitation is matched against, come from platform-auth's users.
PLATFORM_ORG_USER_DIRECTORY = "config.user_directory.lookup_users"
# An invitation link sends an invited email with no account to signup
# (platform-auth's page, mounted at /auth in routes.ts), else to log in.
PLATFORM_ORG_ACCOUNT_EXISTS = "config.user_directory.account_exists"
PLATFORM_ORG_SIGNUP_PAGE = "/auth/signup"
# The invitation link emailed to an invitee (createOrgsPublicRoutes' page).
PLATFORM_ORG_INVITATION_PAGE = "/platform-org/invitations/{token}"
# Invite-only signup (a system setting): who counts as invited.
PLATFORM_AUTH_IS_INVITED = "config.user_directory.has_pending_invitation"
# Reminders and digests can go to the user's email (goalnexa).
GOALNEXA_USER_DIRECTORY = "config.user_directory.lookup_users"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["platform_auth.authentication.ActorAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": [],
    "EXCEPTION_HANDLER": "core_api.exceptions.platform_exception_handler",
    "UNAUTHENTICATED_USER": None,
    # platform_auth's login/signup/setup limits (platform_auth/throttling.py).
    "DEFAULT_THROTTLE_RATES": {
        "auth_login": (os.environ.get("AUTH_LOGIN_RATE") or "10/min"),
        "auth_login_email": (os.environ.get("AUTH_LOGIN_EMAIL_RATE") or "20/hour"),
        "auth_signup": (os.environ.get("AUTH_SIGNUP_RATE") or "10/hour"),
    },
    # Proxies in front of Django that append to X-Forwarded-For - the
    # client IP the limits count by is that many entries from the end.
    # 1 = nginx alone; 2 = nginx behind one more (Cloudflare, a load
    # balancer). Too low and every client shares the proxy's IP (one
    # limit for everyone); too high and a client can fake its IP.
    "NUM_PROXIES": int((os.environ.get("TRUSTED_PROXY_COUNT") or "1")),
}

# Extensions' own settings (e.g. a payment provider's API token), as one
# JSON object of setting name -> value - so a deployment passes them
# through a single environment variable instead of every compose/stack
# file listing each extension's keys. Applied before host_settings below,
# which may read or derive from them.
_extension_settings = json.loads(os.environ.get("GOALNEXA_EXTENSION_SETTINGS") or "{}")
if not isinstance(_extension_settings, dict):
    raise ValueError("GOALNEXA_EXTENSION_SETTINGS must be a JSON object")
globals().update(_extension_settings)

# Last, so an extension sees (and may change) every setting above.
for _extension in GOALNEXA_EXTENSIONS:
    try:
        _host_settings = importlib.import_module(f"{_extension}.host_settings")
    except ModuleNotFoundError as exc:
        if exc.name != f"{_extension}.host_settings":
            raise
        continue
    _host_settings.configure(globals())
