"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib
import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-dev-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

# Comma-separated; docker-compose.yml sets it. Empty = Django's DEBUG
# default (localhost only), which rejects e.g. a Tailscale hostname.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

# nginx passes on X-Forwarded-Proto from the HTTPS front (Tailscale
# serve/Funnel), so absolute URLs Django builds (e.g. the MCP skills
# index) say https:// and CSRF origin checks match.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Full origins (scheme + host), comma-separated - needed for Django's
# own CSRF-protected forms (e.g. /admin/ login) behind HTTPS on a
# domain other than localhost. The API itself uses bearer tokens.
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Strict-Transport-Security max-age. 0 (default) sends no header; set it
# only once the app is served over HTTPS for good - browsers remember it.
SECURE_HSTS_SECONDS = int((os.environ.get("DJANGO_HSTS_SECONDS") or "0"))

# "self_hosted" (default) or "saas". A hosted install lets strangers sign
# up, so it turns off first-run setup (the first account would otherwise
# become app-wide Admin) - see AUTH_FIRST_RUN_SETUP below.
DEPLOYMENT_MODE = os.environ.get("DEPLOYMENT_MODE", "self_hosted")
if DEPLOYMENT_MODE not in ("self_hosted", "saas"):
    raise ValueError(f"DEPLOYMENT_MODE must be 'self_hosted' or 'saas', not {DEPLOYMENT_MODE!r}")

# Extra Django apps a downstream build adds (e.g. hosted billing) -
# comma-separated importable module names, pip-installed into this venv
# (docker-compose.yml's BACKEND_EXTRA_PIP). Each one is added to
# INSTALLED_APPS, its `urls` (if any) is mounted at api/v1/
# (config/urls.py), and its `host_settings.configure(settings)` (if any)
# runs at the end of this file to add/override settings. Empty here.
GOALNEXA_EXTENSIONS = [m.strip() for m in os.environ.get("GOALNEXA_EXTENSIONS", "").split(",") if m.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    # Backend rule mirrors the frontend one: a module's backend is an
    # importable Django app (packaged via that module's own
    # pyproject.toml, editable-installed here) rather than a copy - see
    # root AGENTS.md. Login/User/RefreshToken all come from this app.
    'platform_auth',
    # Organization/OrgMembership. Its own JWTBearerAuthentication is
    # unused here - main's own DEFAULT_AUTHENTICATION_CLASSES
    # (platform_auth's ActorAuthentication, above) resolves request.user
    # to a real platform_auth.User already, and platform_org's views only
    # ever read request.user.id, so which one resolved it is invisible
    # to them.
    'platform_org',
    # Goal/Metric/CheckIn - the product's own core domain. No User/Org
    # table of its own either, same "module with no User table" pattern
    # as platform_org above.
    'goalnexa',
    # MCP server over every BaseViewSet above + personal access tokens
    # for MCP clients. Mounted at api/v1/mcp (config/urls.py).
    'platform_mcp',
    *GOALNEXA_EXTENSIONS,
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files (the admin's) from gunicorn - no
    # separate file server in front of the backend.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL (e.g. postgres://user:pass@host:5432/goalnexa) - unset =
# the local SQLite file, fine for a single-user self-host. Postgres for
# anything with real traffic or more than one backend process.
DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get("DATABASE_URL") or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=int((os.environ.get("DATABASE_CONN_MAX_AGE") or "60")),
        conn_health_checks=True,
    )
}


# Shared by every gunicorn worker (and replica) - the auth rate limits
# count here, and a per-process cache would give each worker its own
# count. The table comes from `manage.py createcachetable`, which the
# compose files run with migrate.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# `manage.py collectstatic` target (the backend image runs it at build).
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Compressed, not Manifest: a manifest storage raises on any file
    # missing from the manifest, which breaks tests/dev that never ran
    # collectstatic.
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# --- platform_auth app config (same settings it reads via django.conf.settings
# in its own security.py/views - see apps/platform-auth/backend/config/settings.py
# for the reference values) ---
JWT_SECRET = os.environ.get("JWT_SECRET", "dev-only-insecure-jwt-secret")
JWT_ACCESS_TTL_MINUTES = float(os.environ.get("JWT_ACCESS_TTL_MINUTES", "15"))
JWT_REFRESH_TTL_DAYS = int(os.environ.get("JWT_REFRESH_TTL_DAYS", "30"))
REFRESH_COOKIE_NAME = "refresh_token"
REFRESH_COOKIE_SECURE = os.environ.get("DJANGO_DEBUG", "true").lower() != "true"
# main is the top-level app, not mounted under a gateway path prefix
# itself - unlike platform-auth's own standalone deployment (which sets
# this to e.g. "/platform-auth"), this stays empty.
URL_PREFIX = ""
# First-run setup (the first account becomes app-wide Admin). Off when
# hosted: signup works from the first account on, and the operator's
# own admin comes from `manage.py grant_role <email> Admin`.
AUTH_FIRST_RUN_SETUP = DEPLOYMENT_MODE != "saas"

# --- platform_mcp app config (all optional) ---
# The MCP server's serverInfo name.
MCP_SERVER_NAME = "goalnexa"
# What every personal access token starts with - makes a leaked one
# recognizable (e.g. to secret scanners) and tells it apart from a JWT.
MCP_TOKEN_PREFIX = "gnx_"

# RBAC (platform_auth.rbac) on every BaseViewSet resource, via
# platform-core's access-policy hook - see platform-auth's AGENTS.md.
CORE_API_ACCESS_POLICY = "platform_auth.rbac.policy.RBACPolicy"
# A role can be held app-wide or within one organization.
RBAC_SCOPE_ENDPOINT = "/api/v1/orgs"
RBAC_SCOPE_LABEL = "Organization"
# Created on migrate when missing. Member (every new user, app-wide) gets
# the everyday resources; managing users/roles is Admin's.
RBAC_DEFAULT_ROLES = [
    {"name": "Admin", "description": "Full access, including users and roles.", "grants_all": True},
    {
        "name": "Member",
        "description": "Everyday use: goals, metrics, check-ins, organizations.",
        "is_default": True,
        # Within an org, who may manage its members and invitations is the
        # org's own owner/admin role (platform-org's OrgRole), on top of this.
        "permissions": ["goals.*", "goal-members.*", "metrics.*", "check-ins.*", "orgs.*", "org-members.*", "org-invitations.*"],
    },
    {
        "name": "Viewer",
        "description": "Read-only - e.g. held within one organization.",
        "permissions": ["goals.view", "goal-members.view", "metrics.view", "check-ins.view", "orgs.view", "org-members.view"],
    },
]

# platform-org has no User table: members' names/emails, and the email an
# invitation is matched against, come from platform-auth's users.
PLATFORM_ORG_USER_DIRECTORY = "config.user_directory.lookup_users"
# An invitation link sends an invited email with no account to signup
# (platform-auth's page, mounted at /auth in routes.ts), else to log in.
PLATFORM_ORG_ACCOUNT_EXISTS = "config.user_directory.account_exists"
PLATFORM_ORG_SIGNUP_PAGE = "/auth/signup"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["platform_auth.authentication.ActorAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": [],
    "EXCEPTION_HANDLER": "core_api.exceptions.platform_exception_handler",
    "UNAUTHENTICATED_USER": None,
    # platform_auth's login/signup/setup limits (platform_auth/throttling.py).
    "DEFAULT_THROTTLE_RATES": {
        "auth_login": (os.environ.get("AUTH_LOGIN_RATE") or "10/min"),
        "auth_login_email": (os.environ.get("AUTH_LOGIN_EMAIL_RATE") or "20/hour"),
        "auth_signup": (os.environ.get("AUTH_SIGNUP_RATE") or "10/hour"),
    },
    # Proxies in front of Django that append to X-Forwarded-For - the
    # client IP the limits count by is that many entries from the end.
    # 1 = nginx alone; 2 = nginx behind one more (Cloudflare, a load
    # balancer). Too low and every client shares the proxy's IP (one
    # limit for everyone); too high and a client can fake its IP.
    "NUM_PROXIES": int((os.environ.get("TRUSTED_PROXY_COUNT") or "1")),
}

# Last, so an extension sees (and may change) every setting above.
for _extension in GOALNEXA_EXTENSIONS:
    try:
        _host_settings = importlib.import_module(f"{_extension}.host_settings")
    except ModuleNotFoundError as exc:
        if exc.name != f"{_extension}.host_settings":
            raise
        continue
    _host_settings.configure(globals())
