# Generated by Django 5.2.17 on 2026-09-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_goals', to='goalnexa.goal'),
        ),
        migrations.AddField(
            model_name='metric',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_metrics', to='goalnexa.metric'),
        ),
    ]
