# Generated by Django 5.2.17 on 2026-09-23 02:22

import django.utils.timezone
from django.db import migrations, models


def backfill_checked_in_at(apps, schema_editor):
    # Existing rows: the reading was taken when the row was written - the
    # AddField default (migration time) would put every old check-in at
    # the same moment.
    CheckIn = apps.get_model("goalnexa", "CheckIn")
    CheckIn.objects.update(checked_in_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0002_goal_parent_metric_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checked_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this reading was taken. Leave blank for now.'),
        ),
        migrations.RunPython(backfill_checked_in_at, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['metric', 'checked_in_at'], name='check_in_metric_time_idx'),
        ),
    ]
