# Generated by Django 5.2.17 on 2026-09-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0003_check_in_checked_in_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name': 'check-in', 'verbose_name_plural': 'check-ins'},
        ),
    ]
