# Generated by Django 5.2.17 on 2026-09-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0004_check_in_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='base_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Where the metric starts - progress is measured from here.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='metric',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text="The latest check-in's value. Left blank on a new metric, it starts at the base value.", max_digits=14),
        ),
    ]
