# Generated by Django 5.2.17 on 2026-09-26 14:43

import core_api.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0006_metric_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_default='public', default='public', help_text="Public: every member of its organization sees it. Private: only you and the goal's members.", max_length=16),
        ),
        migrations.CreateModel(
            name='GoalMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('goal', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='goalnexa.goal')),
            ],
            options={
                'verbose_name': 'goal member',
                'db_table': 'goal_member',
                'constraints': [models.UniqueConstraint(fields=('goal', 'user_id'), name='uq_goal_member_goal_user')],
            },
        ),
    ]
