# Generated by Django 5.2.17 on 2026-09-30 04:03

import core_api.utils
from django.db import migrations, models
from django.db.models import Max
from django.utils import timezone


def backfill(apps, schema_editor):
    """Existing metrics' last check-in time, and every goal's progress and
    health - otherwise they'd read "unknown" until their next check-in.
    Uses goalnexa.progress's pure math on the historical models (plain
    attribute access, no model methods)."""
    from goalnexa.progress import compute_goal

    Goal = apps.get_model("goalnexa", "Goal")
    Metric = apps.get_model("goalnexa", "Metric")
    CheckIn = apps.get_model("goalnexa", "CheckIn")
    for row in CheckIn.objects.values("metric_id").annotate(last=Max("checked_in_at")):
        Metric.objects.filter(id=row["metric_id"]).update(last_checked_in_at=row["last"])
    today = timezone.localdate()
    for goal in Goal.objects.all():
        metrics = list(Metric.objects.filter(goal_id=goal.id))
        check_ins = {}
        if goal.target_date is not None:
            for check_in in CheckIn.objects.filter(metric__goal_id=goal.id):
                check_ins.setdefault(check_in.metric_id, []).append(check_in)
        Goal.objects.filter(id=goal.id).update(**compute_goal(goal, metrics, check_ins, today))




class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0007_goal_visibility_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('urls', models.TextField(blank=True, default='')),
                ('app_url', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'reminder settings',
                'verbose_name_plural': 'reminder settings',
                'db_table': 'reminder_settings',
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='health',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track'), ('achieved', 'Achieved')], db_default='unknown', default='unknown', help_text='Where the goal is heading: from its projected progress at the target date.', max_length=16),
        ),
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mean progress of its root metrics, in %.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='projected_progress',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Progress expected by the target date if each metric keeps its check-in trend, in %.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='aggregation',
            field=models.CharField(choices=[('latest', 'The new value (a reading)'), ('sum', 'An amount to add to the total')], db_default='latest', default='latest', help_text='A reading (weight, revenue to date) or an amount done (km run, calls made) - then the metric is the base plus all of them.', max_length=16, verbose_name='each check-in is'),
        ),
        migrations.AddField(
            model_name='metric',
            name='check_in_due_at',
            field=models.DateTimeField(blank=True, help_text='When the next check-in is due.', null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='check_in_every',
            field=models.CharField(blank=True, choices=[('', 'No schedule'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_default='', default='', help_text='How often this metric should get a check-in - an overdue one is flagged and reminded.', max_length=16),
        ),
        migrations.AddField(
            model_name='metric',
            name='ingest_token_hash',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='metric',
            name='ingest_token_hint',
            field=models.CharField(blank=True, db_default='', default='', help_text="The end of this metric's ingest token, if it has one.", max_length=8),
        ),
        migrations.AddField(
            model_name='metric',
            name='last_checked_in_at',
            field=models.DateTimeField(blank=True, help_text='When the latest check-in was taken.', null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Kept by check-ins: the latest one's value, or the base plus all of them. Left blank on a new metric, it starts at the base value.", max_digits=14),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
