# Generated by Django 5.2.17 on 2026-09-30 08:41

import core_api.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0008_freshness_health_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_id', models.UUIDField()),
                ('org_id', models.UUIDField(blank=True, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('closed', 'Closed')], db_default='active', default='active', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('retro', models.TextField(blank=True, default='', help_text="What went well, what didn't - written when closing.")),
            ],
            options={
                'db_table': 'cycle',
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='author_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('agent', 'AI agent'), ('ingest', 'Ingest URL')], db_default='web', default='web', max_length=16),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='digest',
            field=models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly')], db_default='weekly', default='weekly', max_length=8),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='digest_hour',
            field=models.PositiveSmallIntegerField(db_default=8, default=8),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='digest_weekday',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='last_digest_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='timezone',
            field=models.CharField(db_default='UTC', default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='goal',
            name='cycle',
            field=models.ForeignKey(blank=True, db_column='cycle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='goalnexa.cycle'),
        ),
        migrations.CreateModel(
            name='GoalComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('body', models.TextField()),
                ('check_in', models.ForeignKey(blank=True, db_column='check_in_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='goalnexa.checkin')),
                ('goal', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goalnexa.goal')),
            ],
            options={
                'verbose_name': 'goal comment',
                'db_table': 'goal_comment',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('verb', models.CharField(choices=[('goal_created', 'Created the goal'), ('goal_changed', 'Changed the goal'), ('metric_added', 'Added a metric'), ('metric_changed', 'Changed a metric'), ('metric_removed', 'Removed a metric'), ('checked_in', 'Checked in'), ('check_in_changed', 'Changed a check-in'), ('check_in_removed', 'Removed a check-in'), ('health_changed', 'Health changed'), ('commented', 'Commented'), ('scored', 'Scored in a cycle')], max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='goalnexa.goal')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'db_table': 'activity',
                'indexes': [models.Index(fields=['goal', 'created_at'], name='activity_goal_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoalScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('outcome', models.CharField(choices=[('achieved', 'Achieved'), ('partial', 'Partial'), ('missed', 'Missed'), ('dropped', 'Dropped')], max_length=16)),
                ('final_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('final_health', models.CharField(choices=[('unknown', 'Unknown'), ('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track'), ('achieved', 'Achieved')], default='unknown', max_length=16)),
                ('reflection', models.TextField(blank=True, default='')),
                ('cycle', models.ForeignKey(db_column='cycle_id', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='goalnexa.cycle')),
                ('goal', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='goalnexa.goal')),
                ('rolled_to', models.ForeignKey(blank=True, db_column='rolled_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_from', to='goalnexa.goal')),
            ],
            options={
                'verbose_name': 'goal score',
                'db_table': 'goal_score',
                'constraints': [models.UniqueConstraint(fields=('goal', 'cycle'), name='uq_goal_score_goal_cycle')],
            },
        ),
        migrations.CreateModel(
            name='GoalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('progress', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('projected_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('health', models.CharField(choices=[('unknown', 'Unknown'), ('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track'), ('achieved', 'Achieved')], default='unknown', max_length=16)),
                ('goal', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='goalnexa.goal')),
            ],
            options={
                'db_table': 'goal_snapshot',
                'constraints': [models.UniqueConstraint(fields=('goal', 'date'), name='uq_goal_snapshot_goal_date')],
            },
        ),
    ]
