# Generated by Django 5.2.17 on 2026-10-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0009_cycles_feed_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersettings',
            name='email',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
