# Generated by Django 5.2.17 on 2026-10-04 16:53

import core_api.utils
import goalnexa.models.dashboard_share
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0010_reminder_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField()),
                ('token', models.CharField(default=goalnexa.models.dashboard_share.generate_share_token, editable=False, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('goal_ids', models.JSONField(default=list)),
                ('hidden_metric_ids', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'dashboard_share',
                'ordering': ['-created_at'],
            },
        ),
    ]
