# Generated by Django 5.2.17 on 2026-10-09 16:10

from itertools import groupby

from django.db import migrations, models


def seed_positions(apps, schema_editor):
    """Number each sibling group in the order the app showed it until now:
    goals by title, metrics by name."""
    Goal = apps.get_model("goalnexa", "Goal")
    Metric = apps.get_model("goalnexa", "Metric")
    goals = Goal.objects.all()
    # Top-level goals are siblings within an org, or within one owner's personal goals.
    key = lambda g: (g.parent_id, g.org_id, g.owner_id if g.org_id is None and g.parent_id is None else None)  # noqa: E731
    for _, group in groupby(sorted(goals, key=lambda g: (str(key(g)), g.title.lower(), str(g.id))), key=lambda g: str(key(g))):
        for i, goal in enumerate(group):
            Goal.objects.filter(pk=goal.pk).update(position=i)
    metrics = sorted(Metric.objects.all(), key=lambda m: (str(m.goal_id), str(m.parent_id), m.name.lower(), str(m.id)))
    for _, group in groupby(metrics, key=lambda m: (m.goal_id, m.parent_id)):
        for i, metric in enumerate(group):
            Metric.objects.filter(pk=metric.pk).update(position=i)


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0011_dashboard_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='position',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='position',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.RunPython(seed_positions, migrations.RunPython.noop),
    ]
