# Generated by Django 5.2.17 on 2026-10-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalnexa', '0012_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(unique=True)),
                ('choice', models.CharField(choices=[('web', 'Website'), ('agent', 'AI assistant')], max_length=16)),
            ],
            options={
                'db_table': 'onboarding_choice',
            },
        ),
    ]
